config/routes.rb
Rails.application.routes.draw do

  
  get '/about' =>'pages#about'

  get '/terms' =>'pages#terms'

  get '/privacy' =>'pages#privacy'
  get '/feed' => 'jobs#feed'

  get "signin" => "sessions#new"
  get '/auth/:provider/callback' => 'sessions#create'
  resource :session
  
  get "signup" => "candidates#new", as: "signup"
  get "update" => "candidates#edit", as: "update"
  get "candidates/:id/profile" => "candidates#profile", as: "profile/info"
  resources :candidates do
    resources :works
    resources :educations
    resources :contact_candidates, except: [:show, :index]
  end

  get "register" => "employers#new", as: "register"
  get "/:id/update-profile" => "employers#editprofile", as: "profile/update"
  get "employers/signup" => "employers#home"
  resources :employers do
    collection do
      get 'search'
    end
  end
  get "jobs/add" => "jobs#new", as: "jobs/add"
  resources :jobs do
    collection do
      get 'search'
    end
    resources :applies, except: [:show, :index]
  end 

  
  get "companies/add" => "companies#new", as: "companies/add"
  get "companies/:id/review" => "companies#review", as: "companies/review"
  get "companies/:id/addreview" => "companies#addreview", as: "company/addreview"
  get "companies/:id/interview" => "companies#interview", as: "companies/interview"
  get "companies/:id/addinterview" => "companies#addinterview", as: "company/addinterview"
  get "companies/:id/job" => "companies#job", as: "company/job"
  get "companies/:id/about" => "companies#about", as: "company/about"
  resources :companies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
    resources :interviews, except: [:show, :index]
    resources :follows
  end

  get "tips/add" => "tips#new", as: "tips/add"
  resources :tips do
    resources :comments
  end

  get '/contact' => 'contacts#new'
  resources :contacts

  root 'pages#home'
  

end

app/models/job.rb
class Job < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  belongs_to :employer
  belongs_to :company
  has_many :applies

  extend FriendlyId
  friendly_id :slug_jobs, use: :slugged
  searchkick
  
  def slug_jobs
    [
      :title,
      [:title, :skills],
      [:title, :skills, :email,],
      [:title, :skills, :email, :city],
      [:title, :skills, :email, :city, :zip_code]
    ]
  end

  validates :title, :experience, :position_type, :city, 
  :state, :country,  presence: true
  validates :description, length: { minimum: 25 }

  INDUSTRY = ['Accounting/Audit Tax', 'Administration/Office Support', 'Agriculture/Farming', 'Airlines/Aviation', 'Alcoholic Beverage', "Alternative Disputes Resolution", "Alternative Medicine", "Animation", "Apparel & Fashion", 
    "Architecture & Planning", "Arts & Crafts", "Automotive", "Banking/Finance/Insurance", "Biotechnology", "Broadcast Media", "Building Design/Materials", "Business Management Consulting", "Capital Markets", "Commercial Real Estate",
   "Computer Software", "Computer hardware & Network Security",'Communication', 'Community Services', "Constomer Services",  "Construction", 'Consumer Electronics', 'Consumer Services', "Creative Art Design", "Dairy", "Education Management", "E-Learning", 'Electrical/Electronic Manufacturing','Engineering', "Entertainment", "Food & Beverages", "Information Technology and Services",
    "Hospital & Health Care", "Import and Export", "Internet", "Government", "Legal", 'Logistics/Transportation', 'Manufacturing/Production', "Marketing and Advertising", "Military", "Nonprofit Organization Management",
   "Oil & Energy", "Online Platform", "Professional Training & Coaching", 'Project/Programme Management', "Property Management", "Real Estate","Restaurants", "Research", "Sales Development", "Security and Investigations", "Sports", "Staffing and Recruiting", "Supply Chain/Procurement", "Telecommunication","Tobacco", "Venture Capital & Private Equity", "Vocational Trades & Services", 'Wine and Spirits',"Other"]

  EXPERIENCE = ['Internship', 'Entry-level', 'Mid-level', 'Senior-level', "Associate", "Executive", "Director", "CEO", "Not Applicable"]
  POSITION_TYPE = ['Full Time', 'Part Time', 'Contract', 'Contract', "Contract to Hire", "Temporary", "Other"]
  EXPERIENCE = ['Internship', 'Entry-level', 'Mid-level', 'Senior-level', "Associate", "Executive", "Director", "CEO", "Not Applicable"]
  PAY_RATE = ['Hourly', 'Weekly', 'Monthly', 'Annually']
  TRAVEL_REQUIRED = ["NO", '0 - 20%', '20 - 40%', '40 - 60%', '60 - 80%', "80 - 100%"]
  COMPANY_SIZE = ["1 - 10 Employees", "11 - 50 Employees", "51 - 100 Employees", "101 - 200 Employees", "201 - 500 Employees", "501 - 1,000 Employees", "1,001 - 5,000 Employees", "5,001 - 10,000 Employees", "10,001 - 50,000 Employees","50,001 - 100,000 Employees", "100,001 - 200,000 Employees", "200,001 - 300,000 Employees", "300,001+ Employees"]

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_signin_employer, only: [:create, :edit, :update, :delete, :new]

  def search
    if params[:search].present?
      @jobs = Job.search(params[:search])
    else
      @jobs = Job.order("created_at DESC").limit(10)
    end
  end

  def index
    #@jobs = Job.order("created_at DESC").page(params[:page]).per_page(8)
    @jobs = Job.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    @companies = Company.all.order("created_at DESC")
    #@job.company_id = @company.id
    #@company.job_id = @job.id
  end

  def feed
    @jobs = Job.order("created_at DESC").limit(5)
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @apply = Apply.new
    @apply.job_id = @job_id
    @job = Job.friendly.find(params[:id])
    @companies = Company.all.order("created_at DESC")
  end

  def edit
    @job = Job.friendly.find(params[:id])
  end

  def update
    @job = Job.friendly.find(params[:id])
    if @job.update(job_params)
      flash[:notice]='Job updated successfully'
      redirect_to @job
    else
      render :edit
    end
  end

  def new
    @job = Job.new
    @jobs = Job.order("created_at DESC").limit(8)
  end

  def create
    @job = current_employer.jobs.build(job_params)
    if @job.save
      redirect_to @job, notice: "Job successfully created!"
    else
      render :new
    end
  end

  def destroy
    @job = Job.friendly.find(params[:id])
    @job.destroy
    redirect_to @jobs_url, alert: "Job has been deleted"
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :email, :url, :city, :state, :zip_code, :country, :skills, :salary, :position_type, :pay_rate, :job_length, :travel_required, :employer_id, :candidate_id, :company_id, :company_name, :industry, :logo, :company_size, :website_url, :company_description, :responsibility, :experience)
  end

  def correct_employer
    unless @job = current_employer.jobs.find_by(id: params[:id])
      redirect_to @jobs_url, alert: "Unauthorized access! Sign in or sign up to get in..."
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_application.html.erb
    <a href="#" data-reveal-id="jobapplication" class="radius success button">Apply for this Job&hellip;</a>

<!-- Reveal Modals begin -->
    <div id="jobapplication" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
      <% if @job.email? %>
        <div class="job-apply">
          <h3><%= @job.title %> - <%= @job.city %>, <%= @job.state %>&nbsp; <%= @job.zip_code %> &nbsp;<%= @job.country %></h3><hr>
          <% if current_candidate %>
            
            <%= form_for [@job, @apply] do |f| %>
              <div class="form-group">
                <h4><%= f.label :name %></h4>
                <%= f.text_field :name, value: "#{current_candidate.name}", class: "form-control" 
                 %>
              </div>
              <div class="form-group">
                <h4><%= f.label :email %></h4>
                <%= f.text_field :email, value: "#{current_candidate.email}", class: "form-control"  %>
              </div>
              <div class="form-group">
                <% if current_candidate.phone_number %>
                  <h4><%= f.label :phone %></h4>
                  <%= f.text_field :phone, class: "form-control", value: "#{current_candidate.phone_number}" %>
                <% else %>
                  <h4><%= f.label :phone %></h4>
                  <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890"  %>
                <% end %>
              </div>
              
              <div class="form-group">
                <h4><%= f.label :message, "Cover Letter" %></h4>
                <%= f.text_area :message, class: "form-control", value: "Dear Hiring Manager,  I feel that my skills and experience are a great fit for this position. Please feel free to contact me to arrange an interview. I look forward to learning more about this opportunity.", cols: 40, rows: 5 %>
              </div>
              <div class="form-group">
                <% if current_candidate.resume_url %>
                  <h2 class='right'><%= link_to "resume.pdf", current_candidate.resume_url, :target => "_blank" %></h2>
                  <%#= f.label :resume, "Upload New Resume" %>
                  <%#= f.file_field :resume, class: "form-control" %>
                <% else %>
                  <%= f.label :resume, "Upload Resume" %>
                  <%= f.file_field :resume, class: "form-control" %>
                <% end %>
              </div><br>
              <div class="form-group">
                <%= f.submit "Submit Application", class: 'success button' %>
              </div>
            <% end %>
          <% else %>
            <%= form_for [@job, @apply] do |f| %>
              <div class="form-group">
              <h4><%= f.label :name %></h4>
              <%= f.text_field :name, class: "form-control", placeholder: "Your name"  %>
              </div>
              <div class="form-group">
                <h4><%= f.label :email %></h4>
                <%= f.text_field :email, class: "form-control", placeholder: "name@company.com"  %>
              </div>
              <div class="form-group">
                <h4><%= f.label :phone %></h4>
                <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890"  %>
              </div>
              <div class="form-group">
                <h4><%= f.label :message, "Cover Letter" %></h4>
                <%= f.text_area :message, class: "form-control", value: "Dear Hiring Manager,  I feel that my skills and experience are a great fit for this position. Please feel free to contact me to arrange an interview. I look forward to learning more about this opportunity.", cols: 40, rows: 5 %>
              </div>
              <div class="form-group">
                <%= f.label :resume, "Upload Resume" %>
                <%= f.file_field :resume, class: "form-control"  %>
              </div>
              <div class="form-group">
                <%= f.submit "Submit Application", class: ' success hollow button' %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %> 
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

app/views/jobs/_apply.html.erb
<% if @job.email? %>
      <div class="job-apply">
        
        <% if current_candidate %>
          <h2>Apply on JobsMat</h2><hr>
          <%= form_for [@job, @apply] do |f| %>
          
            <div class="form-group">
            <%= f.text_field :name, value: "#{current_candidate.name}", class: "form-control" 
             %>
            </div>
            <div class="form-group">
              <%= f.text_field :email, value: "#{current_candidate.email}", class: "form-control"  %>
            </div>
            <div class="form-group">
              <% if current_candidate.phone_number %>
                <%= f.text_field :phone, class: "form-control", value: "#{current_candidate.phone_number}" %>
              <% else %>
                <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890"  %>
              <% end %>
            </div>
          
            <div class="form-group">
              <%#= f.label :message,  %>
              <%= f.text_area :message, class: "form-control", value: "Dear Hiring Manager,  I feel that my skills and experience are a great fit for this position. Please feel free to contact me to arrange an interview. I look forward to learning more about this opportunity.", cols: 40, rows: 5 %>
            </div>
            <div class="form-group">
              <% if current_candidate.resume_url %>
                <%= link_to "resume.pdf", current_candidate.resume_url, :target => "_blank" %>
                <%= f.label :resume, "Upload New Resume" %>
                <%= f.file_field :resume, class: "form-control" %>
              <% else %>
                <%= f.label :resume, "Upload Resume" %>
                <%= f.file_field :resume, class: "form-control" %>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.submit "Submit Application", class: 'success button' %>
            </div>
          <% end %>
        <% else %>
          <%= form_for [@job, @apply] do |f| %>
          
            <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Your name"  %>
            </div>
            <div class="form-group">
              <%= f.text_field :email, class: "form-control", placeholder: "name@company.com"  %>
            </div>
            <div class="form-group">
              <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890"  %>
            </div>
            <div class="form-group">
              <%#= f.label :message,  %>
              <%= f.text_area :message, class: "form-control", value: "Dear Hiring Manager,  I feel that my skills and experience are a great fit for this position. Please feel free to contact me to arrange an interview. I look forward to learning more about this opportunity.", cols: 40, rows: 5 %>
            </div>
            <div class="form-group">
              <%= f.label :resume, "Upload Resume" %>
              <%= f.file_field :resume, class: "form-control"  %>
            </div>
            <div class="form-group text-center">
              <%= f.submit "Apply", class: ' success hollow button' %>
            </div>
          <% end %>
        <% end %>
      

          <!-- <div class="text-center">
              
            </div> -->
      </div>
    <% end %> 

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :multipart => true } do |f| %>
  <%= render "shared/errors", object: @job %>
  
    <div class='form-group'>
      <div class='row'>
        <div class='large-8 medium-7 columns'>
          <%= f.label :company_name, class: 'control-label' %>
          <%= f.text_field :company_name, autofocus: true, placeholder: "Company Name", class: "form-control" %>
        </div>
       <div class='large-4 medium-5 columns'>
           <%= f.label :logo, "Company Logo", class: 'control-label' %>
           <%= f.file_field :logo %>
        </div>
      </div>
    </div>
    
    <div class='form-group'>
      <div class='row'>
        <div class='small-6 columns'>
          <%= f.label :industry, class: 'control-label' %>
          <%= f.select :industry, Job::INDUSTRY, prompt: "Select one", class: "form-control" %>
        </div>
        <div class='small-6 columns'>
          <%= f.label :company_size, class: 'control-label' %>
          <%= f.select :company_size, Job::COMPANY_SIZE, prompt: "Select one", class: "form-control" %>
        </div>
      </div>
    </div>
    
     <div class='form-group'>
      <div class='row'>
         <div class='medium-6 columns'>
           <%= f.label :website_url, "Company Website", class: 'control-label' %>
          <%= f.text_field :website_url, placeholder: "http://companyname.com", class: "form-control" %>
        </div>
        <div class='medium-6 columns'>
          <%= f.label :title, class: 'control-label' %>
          <%= f.text_field :title, placeholder: "Job title", class: "form-control" %>
        </div>
      </div>
    </div>
   
    <div class='form-group'>
      <div class='row'>
         <div class='medium-12 columns'>
            <%= f.label :company_description, class: 'control-label' %>
            <%= f.text_area :company_description, cols: 40, rows: 7, placeholder: "Brief description about your company, what you are up to, service and product" %>
          </div><br>
          <div class='medium-12 columns'>
            <%= f.label :description, class: 'control-label' %>
            <%= f.text_area :description, cols: 40, rows: 7, placeholder: "Job description", :class => 'ckeditor' %>
          </div>
        </div>
      </div><br>
     
    
    <div class='form-group'>
      <%= f.label :skills, class: 'control-label' %>
      <%= f.text_area :skills, cols: 40, rows: 7, :class => 'ckeditor' %>
    </div><br>
    
    <div class='form-group'>
      <%= f.label :responsibility, class: 'control-label' %>
      <%= f.text_area :responsibility, cols: 40, rows: 7, placeholder: "List of job responsibilties", :class => 'ckeditor' %>
    </div>
    
    <div class='form-group'>
      <%= f.label :city, "Location", class: 'control-label' %>
      <div class='row'>
          <div class='medium-6 columns'>
          <%= f.text_field :city, class: "form-control", cols: 20, placeholder: "City e.g Austin" %>
           <%= f.text_field :zip_code, class: "form-control", placeholder: "Zip code e.g 78701" %></div>
          <div class='medium-6 columns'>
            <%= f.text_field :state, class: "form-control", placeholder: "State e.g Texas" %>
            <%= f.text_field :country, class: "form-control", placeholder: "Country e.g USA" %>
          </div>
        </div>
    </div>
    
    
    <div class='form-group'>
      <%= f.label :salary, "Pay Rate", class: 'control-label' %>
      <div class='row'>
        <div class='medium-8 small-7 columns'>
          <%= f.text_field :salary, class: "form-control", placeholder: "Salary Range" %></div>
        <div class='medium-4 small-5 columns'>
          <%= f.select :pay_rate, Job::PAY_RATE, prompt: "Select one", class: "form-control" %>
        </div>
    </div>
    
    
    <div class='form-group'>
      <div class='row'>
        <div class='medium-4 columns'>
          <%= f.label :position_type, class: 'control-label' %>
          <%= f.select :position_type, Job::POSITION_TYPE, prompt: "Select one", class: "form-control" %>
        </div>
        <div class='medium-4 columns'>
          <%= f.label :experience, class: 'control-label' %> 
          <%= f.select :experience, Job::EXPERIENCE, prompt: "Select one", class: "form-control" %>
        </div>
         <div class='medium-4 columns'>
            <%= f.label :travel_required, class: 'control-label' %>
            <%= f.select :travel_required, Job::TRAVEL_REQUIRED, prompt: "Select one", class: "form-control" %>
          </div>
         </div>
      </div>

      
    <div class='form-group'>
      <div class='row'>
        <div class='medium-5 columns'>
          <%= f.label :email, class: 'control-label' %>
          <%= f.text_field :email, class: "form-control", placeholder: "apply@companyname.com" %>
        </div> 
        <div class='medium-1 columns text-center'><br><h2 style="color:#43ac6a;">OR</h2></div>
        <div class='medium-6 columns'>
          <%= f.label :url, class: 'control-label' %>
        <%= f.text_field :url, class: "form-control", placeholder: "http://companyname.com/job.html" %>
        </div>
      </div>
    </div>

    
    <div class='form-group'>
      <%= f.submit class: 'success button' %> <%= link_to "Cancel", jobs_path, class: 'secondary hollow button' %>
  </div>
<% end %>
 

app/views/jobs/edit.html.erb
<div class='row'>
  <div class='medium-10 medium-offset-1 columns job-update'>
    <h2>Editing : <%= @job.title %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class='row'>
  <div class='medium-10 medium-centered columns job-searh-form'>
    <%= form_tag search_jobs_path, method: :get do %> 
      <div class="row collapse"> 
        <div class="small-9 columns">
          <%= text_field_tag :search, params[:search], placeholder: "Job title, skills keywords, company name..." %>
        </div>
        <div class="small-3 columns">
          <%= submit_tag 'Job Search', name: nil, class: "warning button postfix " %>
        </div>   
      </div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='medium-8 columns jobs-list'>
    <br>
  <div id="jobs">
    <%= render @jobs %>
  </div>               
   
   
   <div class ="row">
      <div class="digg_pagination"><br>
        <div class="page_info text-center"><br><br>
        <%= will_paginate @jobs %>
          <%#= page_entries_info @jobs %> 
        </div>
        <%#= will_paginate @collection, renderer: BootstrapPagination::Rails, class: 'text-center' %> 
             <%#= will_paginate @jobs, :container => false, class: "paginate-display" %>   
              <%#= will_paginate @jobs, :page_links => false %> 
      </div>
    </div> 
  </div>
  <div class='medium-4 columns'>
    <div class='hidden-for-small-only job-ads-listing'>
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- MasmaSpace News -->
      <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="ca-pub-1207389406711656"
         data-ad-slot="8952579198"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script><br><br>
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- MasmaSpace News -->
      <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="ca-pub-1207389406711656"
         data-ad-slot="8952579198"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>
  </div>
</div>
    

app/views/jobs/index.js.erb
$('#jobs').append('<%= j render(@jobs) %>');
<% if @jobs.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@jobs) %>')
<% else %>
  $('.pagination').remove;
<% end %>
<% sleep 1 %>

app/views/jobs/new.html.erb
<div class='row'>
  
  <div class='new-job'>
    <div class='large-10 large-centered columns job-form'>
      <h1>Post a Job</h1><hr>
      <%= render 'form' %>
    </div>  
  </div>
</div>

app/views/jobs/search.html.erb
<div class='row'>
  <div class='medium-10 medium-centered columns job-searh-form'>
    <%= form_tag search_jobs_path, method: :get do %> 
      <div class="row collapse"> 
        <div class="small-9 columns">
          <%= text_field_tag :search, params[:search], placeholder: "Job title, skills keywords, company name..." %>
        </div>
        <div class="small-3 columns">
          <%= submit_tag 'Job Search', name: nil, class: "warning button postfix " %>
        </div>   
      </div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='medium-8 columns jobs-list'>
    <h1>Search Result</h1><hr>               
    <% @jobs.each do |job| %>
      <div class='small-12 columns job-listing'>
        <div class='row'>
          <div class='medium-2 small-4 columns job-logo '>

            <% if job.logo_url %>
              <%= image_tag job.logo_url %>
            
              <%# elsif job.company_name = @company.name %>
                <%#= image_tag @company.logo_url %>
            
            <% else %>
              <%= image_tag "https://s3.amazonaws.com/inventivelabs/jobinbox/logos/jobinbox1.png" %>
            <% end %>
          </div>
          <div class='medium-6 small-8 columns'><br>
            <h4><%= link_to job.title, job %></h4>
            <h5><%= job.company_name %></h5>
            <%= truncate(job.description.gsub(/(<[^>]+>)/, ''), length: 100) %>
            <%#= link_to "View full job description", job %>
          </div>
          <div class='medium-2 small-5 columns'>
            <%= job.position_type %><br>
            <%= time_ago_in_words(job.created_at) %> ago
          </div>
          <div class='medium-2 small-7 columns'>
           <%= job.city %>, <%= job.state %> <br> <%= job.zip_code %> <%= job.country %>
          </div> 
        </div>
      </div>
    <% end %>
  </div>
     
  <div class='hidden-for-small medium-4 columns'><br><br>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- MasmaSpace News -->
    <ins class="adsbygoogle"
       style="display:inline-block;width:300px;height:600px"
       data-ad-client="ca-pub-1207389406711656"
       data-ad-slot="8952579198"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
</div>
    

app/views/jobs/show.html.erb
<% title @job.title %>
<% meta_description truncate(@job.description.gsub(/(<[^>]+>)/, ''), length: 350) %>
<div class="row">
  <div class="medium-8 small-12 columns">
    <div class="job-top-title">
      <div class="row">
        <div class="medium-2 small-3 columns">
          <% if @job.logo %>
            <%= image_tag @job.logo_url %>
          <% else %>
            <%= image_tag "https://s3.amazonaws.com/inventivelabs/jobsmat/images/jobmat-icon1.png" %>
          <% end %>
        </div>
        <div class="medium-10 small-9 columns">
          <div class="row">
            <div class="small-12 columns">
              <h2><%= @job.title %></h2>
            </div>
            <div class="medium-8 small-12 columns">
              
              <p><span><%= @job.company_name %></span><br>
              <%= @job.city if @job.city %>, <%= @job.state if @job.state %>&nbsp; <%= @job.zip_code if @job.zip_code %>&nbsp; <%= @job.country if @job.country %><br> Posted <%= time_ago_in_words(@job.created_at) %> ago
              </p>
            </div>
            <div class="medium-4 small-12 columns">
              <% if !@job.email? %>
                <%= link_to "Apply on Career Site", @job.url, :target => "_blank", class: "success expanded button" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
 
    <div class="job-body">
      <h3>Job Description</h3>
      <% if @job.position_type %>
        <h5>Job Type: <%= @job.position_type %> </h5>
      <% end %>
      <%# if @job.salary %>
     <!--  <h5>Salary: <%#= number_to_currency(@job.salary) %>&nbsp; <%#= @job.pay_rate %></h5> -->
      <%# else %>
      <!-- <h5>Salary: Not Specified</h5> -->
      <%# end %>

      <%= @job.description.html_safe %><br>

      <% if @job.responsibility %>
        <h3>Responsibilities</h3>
        <%= @job.responsibility.html_safe %>
      <% end %>

      <% if @job.skills %>
        <h3>Job Requirements/Skills</h3>
        <%= @job.skills.html_safe %>
      <% end %>

      <% if (@job.position_type || @job.industry || @job.experience || @job.travel_required) %>
        <h2>JOB SNAPSHOT</h2>
      <% end %>
      <% if @job.position_type %>
        <h4>Employment Type: <%= @job.position_type %></h4>
      <% end %>
      
      <% if @job.industry %>
        <h4>Industry: <%= @job.industry %></h4>
      <% end %>
      <% if @job.experience %>
        <h4>Experience: <%= @job.experience %></h4>
      <% end %>

      <% if @job.travel_required %>
        <h4>Require travel: <%= @job.travel_required %></h4>
      <% end %>
    </div>

    <div class="job-company-details">
      <h2>About <%= @job.company_name %></h2>
      <span><%= link_to @job.website_url, @job.website_url, :target => "_blank" %></span><br>
        <p><%= @job.company_description %></p>
    </div>
  
    <% if current_employer_admin? %>
      <div class="job-update">
        <%= link_to "Edit", edit_job_path(@job), class: 'success button' %>
        <%= link_to "Delete", job_path(@job), method: :delete, data: {confirm: 'Are you sure?' }, class: 'alert button' %>
      </div>
    <% end %>
  </div>


  
  <div class="medium-4 small-12 columns job-application">
    <% if @job.email? %>
      <div class='jobsmat '>
        <h4> Apply Now <span>»»»</span></h4>
        <p>Please review all application instructions before applying to <%= @job.company_name %>.</p>
        <div><%= render 'application' %></div>
      </div>
    <% end %> 
    <%#= render 'apply' %>

    <div class="hidden-for-small-only job-ads">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- MasmaSpace News -->
      <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="ca-pub-1207389406711656"
         data-ad-slot="8952579198"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>

    </div><br><br>
     
    
  </div>
</div>
  