config/routes.rb
Rails.application.routes.draw do

  
  get '/about' =>'pages#about'

  get '/terms' =>'pages#terms'

  get '/privacy' =>'pages#privacy'
  get '/feed' => 'jobs#feed'

  get "signin" => "sessions#new"
  get '/auth/:provider/callback' => 'sessions#create'
  resource :session
  
  get "signup" => "candidates#new", as: "signup"
  get "update" => "candidates#edit", as: "update"
  get "candidates/:id/profile" => "candidates#profile", as: "profile/info"
  resources :candidates do
    resources :works
    resources :educations
    resources :contact_candidates, except: [:show, :index]
  end

  get "register" => "employers#new", as: "register"
  get "/:id/update-profile" => "employers#editprofile", as: "profile/update"
  get "employers/signup" => "employers#home"
  resources :employers do
    collection do
      get 'search'
    end
  end
  get "jobs/add" => "jobs#new", as: "jobs/add"
  resources :jobs do
    collection do
      get 'search'
    end
    resources :applies, except: [:show, :index]
  end 

  
  get "companies/add" => "companies#new", as: "companies/add"
  get "companies/:id/review" => "companies#review", as: "companies/review"
  get "companies/:id/addreview" => "companies#addreview", as: "company/addreview"
  get "companies/:id/interview" => "companies#interview", as: "companies/interview"
  get "companies/:id/addinterview" => "companies#addinterview", as: "company/addinterview"
  get "companies/:id/job" => "companies#job", as: "company/job"
  get "companies/:id/about" => "companies#about", as: "company/about"
  resources :companies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
    resources :interviews, except: [:show, :index]
    resources :follows
  end

  get "tips/add" => "tips#new", as: "tips/add"
  resources :tips do
    resources :comments
  end

  get '/contact' => 'contacts#new'
  resources :contacts

  root 'pages#home'
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  mount_uploader :company_image, CompanyImageUploader
  mount_uploader :logo, LogoUploader
  belongs_to :employer
  belongs_to :candidate
  has_many :jobs
  has_many :reviews, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows, source: :candidate
  has_many :followers, through: :follows, source: :employer

  extend FriendlyId
  friendly_id :slug_companies, use: :slugged
  searchkick
  
 INDUSTRY = ['Accounting/Audit Tax', 'Administration/Office Support', 'Agriculture/Farming', 'Airlines/Aviation', 'Alcoholic Beverage', "Alternative Disputes Resolution", "Alternative Medicine", "Animation", "Apparel & Fashion", 
    "Architecture & Planning", "Arts & Crafts", "Automotive", "Banking/Finance/Insurance", "Biotechnology", "Broadcast Media", "Building Design/Materials", "Business Management Consulting", "Capital Markets", "Commercial Real Estate",
   "Computer Software", "Computer hardware & Network Security",'Communication', 'Community Services', "Constomer Services",  "Construction", 'Consumer Electronics', 'Consumer Services', "Creative Art Design", "Dairy", "Education Management", "E-Learning", 'Electrical/Electronic Manufacturing', 'Engineering', "Entertainment", "Food & Beverages", "Information Technology and Services",
    "Hospital & Health Care", "Import and Export", "Internet", "Government", "Legal", 'Logistics/Transportation', 'Manufacturing/Production', "Marketing and Advertising", "Military", "Nonprofit Organization Management",
   "Oil & Energy", "Online Platform", "Professional Training & Coaching", 'Project/Programme Management', "Property Management", "Real Estate","Restaurants", "Research", "Sales Development", "Security and Investigations", "Sports", "Staffing and Recruiting", "Supply Chain/Procurement", "Telecommunication", "Tobacco", "Venture Capital & Private Equity", "Vocational Trades & Services", 'Wine and Spirits',"Other"]

  SIZE = ["1 - 10 Employees", "11 - 50 Employees", "51 - 100 Employees", "101 - 200 Employees", "201 - 500 Employees", "501 - 1000 Employees", "1001 - 5000 Employees", "5001 - 10000 Employees", "10001 - 20000 Employees", "20001 - 50000 Employees", "50001 - 100000 Employees", "100001 - 200000 Employees", "200000+ Employees"]
  
  def slug_companies
    [
      :name,
      [:name, :industry],
      [:name, :industry, :founded,],
      [:name, :industry, :founded, :size],
      [:name, :industry, :founded, :size, :location]
    ]
  end
  def company_job
    (company.jobs).size
  end

  def company_jobs
    select(jobs) { |job| job.company_name == company.name}.size
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :delete]
  before_action :set_company, only: [:show, :edit, :update, :destroy, :review, :interview, :addreview, :job, :addinterview]
  before_action :set_company_info, only: [:show, :edit, :update, :destroy, :review, :interview, :addreview, :job, :addinterview]

  def search
    if params[:search].present?
      @companies = Company.search(params[:search])
    else
      @companies = Company.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
    end
    @reviews = Review.all.order("created_at DESC").limit(5)
  end

  def index
    @review = Review.new
    @review.company_id = @company_id
    #@job.company_id = @company_id
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
    @companies = Company.all.order("created_at DESC").limit(6)
    @jobs = Job.all.order("created_at DESC")
    #@jobs = @company.jobs.all
    @companies = Company.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path, notice: "Company added successfully"
    else
      render :new
    end
  end

  def show
    @jobsss = Job.all.order("created_at DESC")
    # @jobs = @jobs.where(title: params["title"]) if params["title"].present?
    # @jobs = @jobs.where(city: params["city"]) if params["city"].present?
  end

  def job

  end

  def addinterview  
  end


  def interview
  end

  def addreview
  end

  def review
    @reviews = Review.where(company_id: @company.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def edit
    @company = Company.friendly.find(params[:id])
  end

  def update
    @company = Company.friendly.find(params[:id])
    if @company.update(company_params)
      redirect_to @company, notice: "Company Updated"
    else
      render :edit
    end
  end

  private

  def set_company_info
    @review = Review.new
    @review.company_id = @company_id
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
    @jobbs = Job.all.order("created_at DESC").select do |job| (job.company_name == @company.name) || (job.website_url == @company.website)
    end
   
    @company.job_id = @job_id
    @jobss = Job.all.order("created_at DESC")
    @followers = @company.followers
    if current_candidate || current_employer
      @current_follow = (current_candidate || current_employer).follows.find_by(company_id: @company.id)
    end
    @reviews = Review.where(company_id: @company.id).order("created_at DESC")
    @reviewss = Review.where(company_id: @company.id).order("created_at DESC")
    @companies = Company.all.order("created_at DESC").limit(8)
    #@jobs = @company.jobs.order("created_at DESC")
    #@jobs = Job.where(company_id: @company.id).order("created_at DESC")
    @interview = Interview.new
    @interview.company_id = @company_id
    @interviewss = Interview.where(company_id: @company.id).order("created_at DESC")
    @interviews = Interview.where(company_id: @company.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 2) 
  end

  def set_company
    @company = Company.friendly.find(params[:id])
  end
  def company_params
    params.require(:company).permit(:name,:about, :founded, :size,:industry,:location,:website,:subsidiaries, :facebook, :twitter, :linkedin, :youtube, :video, :instagram, :googleplus, :pinterest, :github, :slug, :employer_id,:logo, :company_image, :twitter_username, :twitter_widget_id, :facebook_username, :twitter_widget, :candidate_id, :job_id)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/myshare/_aside.html.erb
<!-- <%# if @followers.any? %>
  <div class='company-social company'>
    <h3>Followers</h3>
    <%# @followers.each do |follower| %>
      <div class='row'>
        <div class='large-2 medium-3 small-2 columns'>
          
        </div>
      </div>
    <%# end %>
  </div>
<%# end %> -->


<% if @company.facebook? || @company.twitter? || @company.youtube? || @company.linkedin? || @company.instagram? %>
      
  <div class='company-social company'>
    <p>Connect with <%= @company.name %></p>
      <div class='social-link facebook'>
        <%= link_to "", @company.facebook, :target => "_blank", class: "fa fa-facebook fa-2x" if @company.facebook? %>
      </div>
      <div class='social-link twitter'>
        <%= link_to "", @company.twitter, :target => "_blank", class: "fa fa-twitter fa-2x" if @company.twitter? %>
      </div>
      <div class='social-link youtube'>
        <%= link_to "", @company.youtube, :target => "_blank", class: "fa fa-youtube fa-2x" if @company.youtube? %>
      </div>
      <div class='social-link linkedin'>
        <%= link_to "", @company.linkedin, :target => "_blank", class: "fa fa-linkedin fa-2x" if @company.linkedin? %>
      </div>
      <div class='social-link instagram'>
        <%= link_to "", @company.instagram, :target => "_blank", class: "fa fa-instagram fa-2x" if @company.instagram? %>
      </div>
      <div class='social-link googleplus'>
        <%= link_to "", @company.googleplus, :target => "_blank", class: "fa fa-google-plus fa-2x" if @company.googleplus? %>
      </div>
      <div class='social-link pinterest'>
        <%= link_to "", @company.pinterest, :target => "_blank", class: "fa fa-pinterest-p fa-2x" if @company.pinterest? %>
      </div>
      <% if @company.github? %>
        <div class='social-link github'>
          <%= link_to "", @company.github, :target => "_blank", class: "fa fa-github-alt fa-2x" %>
        </div>
      <% end %>
    </div>
<% end %> 
<% if @company.facebook_username? || @company.twitter_username? %>
  <div class='hide-for-medium-down company-follow company'>
    <p>Follow <%= @company.name.capitalize %></p>
    <ul class="tabs" data-tab role="tablist">
      <% if @company.facebook_username? %>
        <li class="tab-title " role="presentation"><a href="#facebook" role="tab" tabindex="0" aria-selected="true" aria-controls="facebook"><span class='facebook-so'><i class='fa fa-facebook'></i>Facebook</span></a></li>
      <% end %>
      <% if @company.twitter_username? && @company.twitter_widget_id? %>
        <li class="tab-title active" role="presentation"><a href="#twitter" role="tab" tabindex="0" aria-selected="false" aria-controls="twitter"><span class='twitter-so'><i class='fa fa-twitter'></i>Twitter</span></a></li>
      <% end %>
    </ul>
    <div class="tabs-content">
      <section role="tabpanel" aria-hidden="false" class="content active" id="facebook">
        <div class='social-tab'><%= render partial: "companies/myshare/facebook" %>
        </div>
      </section>
      <section role="tabpanel" aria-hidden="true" class="content" id="twitter">
       <div class='social-tab'><%= render partial: "companies/myshare/twitter" %></div>
      </section>
      
    </div>
  </div>
<% end %>
<% if @company.video? %>
  <div class='company-video company'>
    <% if @company.video %><br>
      <div class='company-video-content'>
        <p>Company Video</p>
        <p><iframe  src="//www.youtube.com/embed/<%= @company.video %>" frameborder="0" allowfullscreen style="width:97%;height:250px;margin:auto;"></iframe>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/companies/myshare/_company_about.html.erb
<div class='company-main-tab'>
  <ul class="tabs" data-tab role="tablist">
    <li class="tab-title active" role="presentation"><a href="#about" role="tab" tabindex="0" aria-selected="true" aria-controls="about">About <%= @company.name %></a></li>
    <li class="tab-title" role="presentation"><a href="#review" role="tab" tabindex="0" aria-selected="false" aria-controls="review">Reviews</a></li>
    <li class="tab-title" role="presentation"><a href="#interview" role="tab" tabindex="0" aria-selected="false" aria-controls="interview">Interview</a></li>
    <% if current_candidate || current_employer %>
      <li class="tab-title" role="presentation"><a href="#add-review" role="tab" tabindex="0" aria-selected="false" aria-controls="add-review">Add Review</a></li>
      <li class="tab-title" role="presentation"><a href="#add-interview" role="tab" tabindex="0" aria-selected="false" aria-controls="add-interview">Add Interview</a></li>
    <% end %>
  </ul>
  <div class="tabs-content ">
    <section role="tabpanel" aria-hidden="false" class="content active" id="about">
     <p><%= @company.about.html_safe %></p>
    </section>
    <section role="tabpanel" aria-hidden="true" class="content" id="review">
        <div>
            <%= render partial: "companies/myshare/showReview" %>
          </div>
    </section>
    <section role="tabpanel" aria-hidden="true" class="content" id="interview">
      <div>
            <%= render partial: "companies/myshare/interview" %>
          </div>
    </section>
    <section role="tabpanel" aria-hidden="true" class="content" id="add-review">
      <div class='small-12 columns review-form'>
        <%= render partial: 'reviews/form' %>
      </div>
    </section>
    <section role="tabpanel" aria-hidden="true" class="content" id="add-interview">
      <div class='small-12 columns interview-form'>
        <h3>Share your experience about <%= @company.name %> job interview process... </h3>
        <%= render partial: 'interviews/form' %>
      </div>
    </section>
  </div>
</div>

app/views/companies/myshare/_company_jobs.html.erb
    <% @jobss.limit(4).each do |job| %>
      <% if (job.company_name == @company.name) || (job.website_url == @company.website) %>
        <div class='medium-12 columns company-main-nav company'> 
          <div class='medium-12 columns company-main-nav company'>
            <span class='h'>Carear At <%= @company.name %></span>
              <span class='more right'>
                <%= link_to "More Jobs", company_job_path(@company) %> 
              <span class='sign'>></span>
            </span>
            <div class='medium-12 columns company-show-job'>
              <div class='medium-2 small-3 columns'><br>
                <%= image_tag @company.logo_url, style: "width:50px;height:50px;" if @company.logo_url %>
              </div>
              <div class='medium-10 small-9 columns'>
                <h2><%= link_to job.title, job %></h2>
                <%= truncate(job.description.gsub(/(<[^>]+>)/, ''), length: 200) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
          

  

app/views/companies/myshare/_facebook.html.erb
<div class="fb-page" data-href="https://www.facebook.com/<%= @company.facebook_username %>" data-tabs="timeline" data-height="350" data-margin-left="20" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/<%= @company.facebook_username %>"><a href="https://www.facebook.com/<%= @company.facebook_username %>"><%= @company.facebook_username %></a></blockquote></div></div>

app/views/companies/myshare/_header.html.erb
<div class='row'>
  <div class='medium-12 columns company'>
    <div class='company-bgimage'>
      <% if @company.company_image_url %>
        <%= image_tag @company.company_image_url.html_safe %>
      <% else %>
      <% end %>
    </div>
    <div class='row'>
      <div class='medium-12 columns company-logo'>
        <% if @company.logo_url %>
          <%= image_tag @company.logo_url.html_safe %>
        <% else %>
        <% end %>
        <span><%= @company.name %></span>
      </div>
      <div class='medium-12 columns company-info'>
        <div class='row'>
          <div class='large-7 medium-12 small-12 columns'>
            <table>
              <thead>
                <tr>
                  <th>
                    <div class='interview-rating text-center'>
                      <%= " " %><br><%= link_to @company.name, company_path(@company) %>
                    </div>
                    </th>
                  <% if @reviews.blank? %>
                  <% else %>
                    <th class= "hide-for-small-only">
                      <div class='review-star'>
                        <div class="star-rating" data-score= <%= @avg_rating %> ></div> 
                      </div>
                    </th> 
                  <% end %>        
                  <th>
                    <div class='interview-rating text-center'>
                      <% if @jobbs.length == 1 %>
                        <%= "#{@jobbs.length} " %><br><%= link_to "Job", company_job_path(@company) %>
                      <% else %>
                        <%= "#{@jobbs.length} " %><br><%= link_to "Jobs", company_job_path(@company) %>
                      <% end %>
                    </div>
                  </th>
                  <th>
                    <div class='review-rating text-center'>
                      <% if @reviewss.length == 1 %>
                        <%= "#{@reviewss.length} " %><br><%= link_to "Review", companies_review_path(@company) %>
                      <% else %>
                        <%= "#{@reviewss.length} " %><br><%= link_to "Reviews", companies_review_path(@company) %>
                      <% end %>
                    </div>
                  </th> 
                  <th>
                    <div class='interview-rating text-center'>
                      <% if @interviewss.length == 1 %>
                        <%= "#{@interviewss.length} " %><br><%= link_to "Interview", companies_interview_path(@company) %>
                      <% else %>
                        <%= "#{@interviewss.length} " %><br><%= link_to "Interviews", companies_interview_path(@company) %>
                      <% end %>
                    </div>
                  </th>
                  <th>
                    <div class='interview-rating text-center'>
                      <% if @followers.length == 1 %>
                        <%= @followers.length %><br> Follower
                      <%#= pluralize(@followers.size, "follower") %>
                      <% else %>
                        <%= @followers.length %><br> Followers
                      <% end %>
                    </div>
                  </th>
                </tr>
              </thead>
            </table> 
          </div>
          <div class='large-5 medium-12 small-12 company-button-header columns'>
            <% if current_employer || current_candidate %>
              <% if @current_follow %>
                <span class=" small secondary button fa fa-check-square-o"><%= link_to " Following", company_follow_path(@company, @current_follow), method: :delete, style: "color:green;font-weight:bold;" %></span>&nbsp;&nbsp; 
              <% else %>
                <span class=" small secondary button"><%= link_to " Follow Us", company_follows_path(@company), style: "color:green;font-weight:bold;" %></span>&nbsp;&nbsp;
              <% end %>
            <% end %>

            <% if current_employer || current_candidate %>
              <div class="button-group" data-grouptype="OR">
                <span class=" small button success radius fa fa-plus"><%= link_to "  Add Review", company_addreview_path(@company) %></span>
                <span class=" small button warning radius fa fa-briefcase "><%= link_to "  Add Interview", company_addinterview_path(@company) %>
                </span>
              </div>
            <% else %>
              <%= link_to 'Signin to Add-Review', signin_path, class: 'small button success radius right' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: "companies/myshare/script" %>

app/views/companies/myshare/_interview.html.erb
<% if @interviews.blank? %>
    <div class='medium-12 columns company-main'>
      <div class='row'>
        <div class='medium-12 columns company-main-top company'>
          <h3>No interviews yet.
            <% if current_employer || current_candidate %>
              Be the first to share your interview process if any with
              <%= link_to @company.name, company_addinterview_path(@company) %></h3>
            <% else %>
              <%= link_to 'Be the first, Signin to Add-Interview', signin_path %>
            <% end %>
        </div>
      </div>
    </div>
  <% else %>
  <div class='row'>
    <div class='medium-12 columns'>
      <div class='row'>
        <div class='medium-12 columns company-main-top company'>
          <h3 class='review-subhead'><%= @company.name %> Interviews</h3>
          <% @interviews.limit(1).each do |interview| %>
            <div class="row ">
              <div class='medium-2 small-3 columns'></div>
              <div class='medium-10 small-9 columns'>
                <%= interview.created_at.strftime("%-m/%-d/%y") %>
              </div><br><br>
              <div class='small-12 columns'>
                <div class='row '>
                  <div class='medium-2 small-3 columns'>
                    <%= image_tag @company.logo_url, style: "width:60px;height:65px;" %>
                  </div>
                  <div class='medium-10 small-9 columns review-rating'>
                    <span style='font-size:22px'><%= interview.job_title %></span><br>
                    <span style='font-size:16px'>Application Process</span><br>
                    <span style='font-size:14px'><%= "I applied via #{interview.how_heard}" if interview.how_heard %>.&nbsp; <%= "The process took #{interview.duration} #{interview.duration_days}" %>.&nbsp;<%= "I interviewed at #{@company.name} #{interview.where}"  %></span>
                    <div class='row'>
                      <div class='medium-4 small-6 columns'>
                        <%= interview.interview_difficulty %> Interview
                      </div>

                      <div class='medium-4 small-6 columns'>
                        <% if interview.hired === "Yes" %>
                          Accepted offer
                        <% else interview.hired === "No" %>
                          No Offer
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class='row '>
              <div class='medium-2 small-3 columns'></div>
              <div class='medium-10 small-9 columns'><br>

                <% if interview.process%>
                  <p><span><b>Interview Process</b></span><br>
                  <%= interview.process %></p>
                <% end %>

                <% if interview.questions %>
                  <span><b>Interview Questions</b></span><br><%= interview.questions %>
                <% end %>

                <% if current_employer || current_candidate %>
                  <% if interview.anwsers %>
                    <p><span><b>Interview Anwsers<b></span><br><%= interview.anwsers %></p>
                  <% end %>
                <% end %><br><br>
                <% if current_employer_admin? %>
              <%= link_to "Edit", edit_company_interview_path(@company, interview) %> |
              <%= link_to "Delete", company_interview_path(@company, interview), method: :delete, data: { confirm: 'Are you sure?' }%>
            <br> <%= link_to" See all interviews", companies_interview_path(@company) %>
            <% end %>
              </div>
            </div>

          <% end %>

        </div>
      </div>
    </div>

  </div>
  <% end %>

app/views/companies/myshare/_main.html.erb
<div class="fade">
  <% @companies.each do |company| %>
    <div>
      <span>
        <%# if company.company_image_url %>
          <%= image_tag company.company_image_url alt: company.name %>
        <%# end %>
        <span class='large-8 large-offset-2 medium-10 medium-offset-1 columns contents'>
          <p>
            <h1 class="hide-for-small-only">Search for Companies by Name</h1>
            <div class="medium-10 medium-offset-1 small-12 columns">
              <%= form_tag search_companies_path, method: :get do %>
                <div class="row collapse">
                  <div class="small-9 columns">
                    <%= text_field_tag :search, params[:search], placeholder: "Search for company by name..." %>
                  </div>
                  <div class="small-3 columns">
                    <%= submit_tag 'Company', name: nil, class: "warning button postfix " %>
                  </div>
                </div>
              <% end %>
            </div>
          </p>
        </span>
        <span class='content show-for-large-up'>
          <%# if company.logo_url %>
            <%= image_tag company.logo_url, alt: company.name %>
          <%# end %>
          <span>
            <h4><%= link_to company.name, company %></h4>
            <p><%= company.industry %></p>
          </span>
        </span>
        <span class='content-medium show-for-medium-only'>
          <%= image_tag company.logo_url, alt: company.name %>
          <span>
            <h4><%= link_to company.name, company %></h4>
          </span>

        </span>
      </span>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.fade').slick({
      dots: true,
      infinite: true,
      speed: 1000,
      fade: true,
      swipe: true,
      autoplay: true,
      autoplaySpeed: 5000,
      cssEase: 'linear'

    });
  });
</script>

app/views/companies/myshare/_review.html.erb
<% @reviews.limit(1).each do |r| %>
<section class="review-bottom">
  <div class="row">
    <div class='medium-2 small-3 columns'>  </div>
    <div class='medium-10 small-9 columns'>
      <%= r.created_at.strftime("%-m/%-d/%y") %>
    </div><br><br>
    <div class='small-12 columns'>
      <div class='row review-subhead'>
        <div class='medium-2 small-3 columns'>
          <%= image_tag @company.logo_url, style: "width:60px;height:65px;" %>
        </div>
        <div class='medium-10 small-9 columns review-rating'>
          <h3><%= r.title %></h3>
          <div class='star-rating' data-score= <%= r.rating %> ></div><br>
          <span><%= r.employee_type %> | Work at <%= @company.name %> on <%= r.employee_status %></span><br>
        </div>
      </div>
      <div class='small-12 columns'>
        <p><span>Pros</span><br><%= h(r.pros).gsub(/\n/, '<br/>').html_safe %></p>
        <p><span>Cons</span><br><%= h(r.cons).gsub(/\n/, '<br/>').html_safe %></p>
        <p><span>Advice</span><br><%= h(r.advice).gsub(/\n/, '<br/>').html_safe %></p>
        <% if @reviewss.length == 1 %>
        <% else %>
          <%= link_to" See all #{@reviewss.length} Reviews", companies_review_path(@company) %>
        <% end %><br>
        <% if current_employer_admin? %>
        <%# if (r.user == current_user) || (current_user.admin?)%>
          <%= link_to "Edit", edit_company_review_path(@company, r) %> | 
          <%= link_to "Delete", company_review_path(@company, r), method: :delete, data: { confirm: 'Are you sure?' }%>
        <% end %><br>
        
      </div>
    </div>
  </div><br>
</section><br>
<% end %>

app/views/companies/myshare/_review_partial.html.erb
<% @reviews.limit(1).each do |r| %>
<div class="row">
    <div class='medium-10 small-9 columns'>Company Review</div>
    <div class='medium-2 small-3 columns'>
      <%= r.created_at.strftime("%-m/%-d/%y") %>
    </div><br><br>
    <div class='small-12 columns'>
      <div class='row review-subhead'>
        <div class='medium-2 small-3 columns'>
          <%= image_tag @company.logo_url, style: "width:60px;height:65px;" %>
        </div>
        <div class='medium-10 small-9 columns review-rating'>
          <h3><%= r.title %></h3>
          <div class='star-rating' data-score= <%= r.rating %> ></div><br>
          <span><%= r.employee_type %> | Work at <%= @company.name %> on <%= r.employee_status %></span><br>
        </div>
      </div><br>
      <div class='small-12 columns'>
        <p><span>Pros</span><br><%= h(r.pros).gsub(/\n/, '<br/>').html_safe %></p>
        <p><span>Cons</span><br><%= h(r.cons).gsub(/\n/, '<br/>').html_safe %></p>
        <p><span>Advice</span><br><%= h(r.advice).gsub(/\n/, '<br/>').html_safe %></p>
        <% if @reviewss.length == 1 %>
        <% else %>
          <%= link_to" See all #{@reviewss.length} Reviews", companies_review_path(@company) %>
        <% end %><br>
        <% if current_employer_admin? %>
        <%# if (r.user == current_user) || (current_user.admin?)%>
          <%= link_to "Edit", edit_company_review_path(@company, r) %> | 
          <%= link_to "Delete", company_review_path(@company, r), method: :delete, data: { confirm: 'Are you sure?' }%>
        <% end %><br>

      </div>
    </div>
  </div><br>
<% end %>

app/views/companies/myshare/_script.html.erb
<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/foodplace/uploads/stars',
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    }
  });  
</script>

app/views/companies/myshare/_showReview.html.erb
<% if @reviews.blank? %>
<h3>No reviews yet.
  <% if current_employer || current_candidate %>
    Be the first to post your review for <h3><%= link_to @company.name, company_addreview_path(@company) %></h3>
  <% else %>
    <%= link_to 'Be the first, Signin to Add-Review', signin_path %>
  <% end %>
<% else %>
  <div class='small-12 columns company-main-job company'>
    <%= render "companies/myshare/review_partial" %>
  </div>
<% end %>

app/views/companies/myshare/_twitter.html.erb
<a class="twitter-timeline" href="https://twitter.com/<%= @company.twitter_username %>" data-widget-id="<%= @company.twitter_widget_id %>">Tweets by @<%= @company.twitter_username %></a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>