config/routes.rb
Rails.application.routes.draw do

  
  get '/about' =>'pages#about'

  get '/terms' =>'pages#terms'

  get '/privacy' =>'pages#privacy'
  get '/feed' => 'jobs#feed'

  get "signin" => "sessions#new"
  get '/auth/:provider/callback' => 'sessions#create'
  resource :session
  
  get "signup" => "candidates#new", as: "signup"
  get "update" => "candidates#edit", as: "update"
  get "candidates/:id/profile" => "candidates#profile", as: "profile/info"
  resources :candidates do
    resources :works
    resources :educations
    resources :contact_candidates, except: [:show, :index]
  end

  get "register" => "employers#new", as: "register"
  get "/:id/update-profile" => "employers#editprofile", as: "profile/update"
  get "employers/signup" => "employers#home"
  resources :employers do
    collection do
      get 'search'
    end
  end
  get "jobs/add" => "jobs#new", as: "jobs/add"
  resources :jobs do
    collection do
      get 'search'
    end
    resources :applies, except: [:show, :index]
  end 

  
  get "companies/add" => "companies#new", as: "companies/add"
  get "companies/:id/review" => "companies#review", as: "companies/review"
  get "companies/:id/addreview" => "companies#addreview", as: "company/addreview"
  get "companies/:id/interview" => "companies#interview", as: "companies/interview"
  get "companies/:id/addinterview" => "companies#addinterview", as: "company/addinterview"
  get "companies/:id/job" => "companies#job", as: "company/job"
  get "companies/:id/about" => "companies#about", as: "company/about"
  resources :companies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
    resources :interviews, except: [:show, :index]
    resources :follows
  end

  get "tips/add" => "tips#new", as: "tips/add"
  resources :tips do
    resources :comments
  end

  get '/contact' => 'contacts#new'
  resources :contacts

  root 'pages#home'
  

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  mount_uploader :cand_image, CandImageUploader
  mount_uploader :resume, ResumeUploader
  has_secure_password
  
  extend FriendlyId
  friendly_id :username, use: :slugged
  # searchkick
  validates :password, length: { minimum: 8, allow_blank: true }

  validates :name, presence: true
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }

  validates :username, presence: true,
                     format: /\A[A-Z0-9]+\z/i,
                     uniqueness: { case_sensitive: false }
  
  has_many :works
  has_many :educations
  has_many :jobs
  has_many :comments
  has_many :companies
  has_many :applies, dependent: :destroy
  has_many :contact_candidates, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followed_companies, through: :follows, source: :company

  PROFILE_STATUS = ["PUBLIC", "PRIVATE"]
  RESUME_STATUS = ["PUBLIC", "PRIVATE"]
  PHONE_STATUS = ["PUBLIC", "PRIVATE"]
  EMAIL_STATUS = ["PUBLIC", "PRIVATE"]

  before_create {generate_token(:auth_token)}

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    CandidateMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Candidate.exists?(column => self[column])
  end

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end
 
  def self.authenticate(email_or_username, password)
    candidate = Candidate.find_by(email: email_or_username) || Candidate.find_by(username: email_or_username)
    candidate && candidate.authenticate(password)
  end

  def should_generate_new_friendly_id?
      new_record?
  end
  
  def p_status
    candidate.profile_status == "PUBLIC"
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  #before_action :require_pro, only: [:index]
  before_action :correct_candidate, only: [:edit, :update, :delete]
  before_action :require_admin, only: [:delete]

  # def search
  #   if params[:search].present?
  #     @candidates = Candidate.search(params[:search])
  #   else
  #     @candidates = Candidate.order("created_at DESC").limit(3)
  #   end
  # end
  
  def index
    @candidates = Candidate.order("created_at DESC")
  end

  def show
    @contact_candidate = ContactCandidate.new
    @contact_candidate.candidate_id = @candidate_id
    @candidate = Candidate.friendly.find(params[:id])
    @work = Work.new
    @work.candidate_id = @work_id
    @works = Work.where(candidate_id: @candidate.id).order("created_at DESC")

    @education = Education.new
    @education.candidate_id = @education_id
    @educations = Education.where(candidate_id: @candidate.id).order("created_at DESC")
    @followed_companies = @candidate.followed_companies
    @jobs = Job.all.order("created_at DESC")
  end

  def new
    @candidate = Candidate.new 
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save 
      session[:candidate_id] = @candidate.id
      CandidateNotifier.send_signup_email(@candidate).deliver_now
      CandidateRegisterNotifierMailer.send_candidate_signup_email_to_admin(@candidate).deliver_now
      redirect_to @candidate, notice: "Thanks for signing up as job applicant"
    else
      render :new
    end
  end

  def edit
    @contact_candidate = ContactCandidate.new
    @contact_candidate.candidate_id = @candidate_id
    @candidate = Candidate.friendly.find(params[:id])
  end

  def profile
    @candidate = Candidate.friendly.find(params[:id])
    @work = Work.new
    @work.candidate_id = @work_id
    @works = Work.where(candidate_id: @candidate.id).order("created_at DESC")

    @education = Education.new
    @education.candidate_id = @education_id
    @educations = Education.where(candidate_id: @candidate.id).order("created_at DESC")
  end


  def update
    @candidate = Candidate.friendly.find(params[:id])
    if @candidate.update(candidate_params)
      redirect_to @candidate
    else
      render :edit
    end
  end

  def destroy
    @candidate = Candidate.friendly.find(params[:id])
    @candidate.destroy
    redirect_to root_path, alert: "Account has been deleted, sorry to see you going!"
  end


  private

  def require_correct_candidate
    @candidate = Candidate.friendly.find(params[:id])
      redirect_to root_url unless current_candidate?(@candidate)
    end

  def candidate_params
    params.require(:candidate).permit(:name,:email,:password,:password_confirmation,:username,:about, :headline, :experience, :education, :desired_salary, :city, :zip_code, :country, :phone_number, :bb_pin, :github_url, :twitter_url, :linkedin_url, :dribbble_url, :facebook_url, :provider, :uid, :auth_token, :skype_id, 
      :availability, :skills, :job_type, :languages, :how_heard, :cand_image, :resume, :projects_link, :portfolio_url, :favorite_website, :image_url, :profile_status, :phone_status, :resume_status, :email_status, :slug)
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def profile_image_for(candidate, options={})
    size = options[:size] || 80
    url = "https://secure.gravatar.com/avatar/#{candidate.gravatar_id}?s=#{size}"
    image_tag(url, alt: candidate.name)
  end
end

app/views/candidates/_contact_candidate.html.erb
<a href="#" data-reveal-id="contact_candidate" class="radius success button" style="width:90%;margin-bottom: -1px;text-align: left;padding-left: 5%;">Send Me Message&hellip;</a>
<% if @candidate.email_status == "PUBLIC" %>
  <a href="mailto:<%= @candidate.email %>"  class="radius success button" style="width:90%;margin-top:-5px;border-top: 1px solid #eaf4ee;text-align: left;padding-left: 5%;">Send E-Mail</a>
<% end %>


<!-- Reveal Modals begin -->
    <div id="contact_candidate" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
        <div class="job-apply">
          <h3>Hi, My name is <%= @candidate.name %>, Feel free to get in touch with me</h3><hr>
          <%= form_for [@candidate, @contact_candidate] do |f| %>
            <div class="form-group">
            <h4><%= f.label :name %></h4>
            <%= f.text_field :name, class: "form-control", placeholder: "Your name"  %>
            </div>
            <div class="form-group">
              <h4><%= f.label :email %></h4>
              <%= f.text_field :email, class: "form-control", placeholder: "name@company.com"  %>
            </div>
            <div class="form-group">
              <h4><%= f.label :message, "Cover Letter" %></h4>
              <%= f.text_area :message, cols: 40, rows: 5 %>
            </div>
            <div class="form-group">
              <%= f.submit "Sent Message", class: ' success hollow button' %>
            </div>
          <% end %>
        </div> 
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <%= render "shared/errors", object: @candidate %>

      <div class="form-group">
        <%= f.text_field :name, size: 50, autofocus: true, placeholder: "Your Full Name" %>
      </div>

      <div class="form-group">
          <%= f.text_field :username, size: 50,
                    placeholder: "Username Alphanumeric characters only!" %>
      </div>

      <div class="form-group">
        <%= f.email_field :email, size: 50, placeholder: "Email Address" %>
      </div>

     <div class="form-group">
        <%= f.password_field :password, size: 50, placeholder: "Password 8 or more characters" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, size: 50, placeholder: "Confirm Password" %>
      </div>

      <div class="form-group">
        <% if @candidate.new_record? %>
          <%= f.submit "Create Account", class: "success hollow button" %>
        <% else %>
          <%= f.submit "Update Account", class: "success hollow button" %>
        <% end %>
      </div>
<% end %>

app/views/candidates/edit.html.erb
<div class='row edit-candidates'>
<div class='medium-3 columns hide-for-small-only'>
    <br><br>
    <div class='cand-profile-image'>
      <% if @candidate.cand_image_url %>
        <%= image_tag @candidate.cand_image_url %>
      <% else %>
        <%= profile_image_for@candidate %></p>
      <% end %>
    </div>
    <div><%= render 'contact_candidate' %></div>
    <%#= @candidate.image_url %>
    <%#= @candidate.headline %>
    <% if current_candidate?(@candidate) %>
      <div class='candidate-edit-nav'>
        <ul>
          <li>
            </i><% if  @candidate.resume_url %>
              <i class='fa fa-briefcase'></i>
              <%= link_to "Résumé", @candidate.resume_url, :target => "_blank" if @candidate.resume_url  %>
            <% else %>
              </i><%= link_to "Upload Résumé", profile_info_path+"#resume" if current_candidate?(@candidate)  %>
            <% end %>
          </li>
          <li><%= link_to "Update Profile", profile_info_path(current_candidate) if current_candidate %></li>
          <li><%= link_to "Settings", edit_candidate_path(current_candidate) if current_candidate %></li>
          <% if @candidate.portfolio_url %> 
            <li><%= link_to "Personal Website", @candidate.portfolio_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.projects_link %>
            <li><%= link_to "Blog/PortFolio", @candidate.projects_link, target: "_blank" %></li>
          <% end %>
          <% if @candidate.linkedin_url %>
            <li><%= link_to "Linkedin", "http://linkedin.com/in/" + @candidate.linkedin_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.twitter_url %>
            <li><%= link_to "Twitter", "http://twitter.com/" + @candidate.twitter_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.github_url %>
            <li><%= link_to "Github", "http://github.com/" + @candidate.github_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.facebook_url %>
            <li><%= link_to "Facebook", "http://facebook.com/" + @candidate.facebook_url, target: "_blank"  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
  </div>

   <div class='small-12 columns hide-for-medium-up'>
    <% if current_candidate?(@candidate) %>
      <div class='candidate-edit-nav-vertical'>
        <ul>
          <li>
            </i><% if  @candidate.resume_url %>
              <i class='fa fa-briefcase'></i>
              <%= link_to "Résumé", @candidate.resume_url, :target => "_blank" if @candidate.resume_url  %>
            <% else %>
              </i><%= link_to "Upload Résumé", profile_info_path+"#resume" if current_candidate?(@candidate)  %>
            <% end %>
          </li>
          <li><%= link_to "Update Profile", profile_info_path(current_candidate) if current_candidate %></li>
          <li><%= link_to "Settings", edit_candidate_path(current_candidate) if current_candidate %></li>
          <% if @candidate.portfolio_url %> 
            <li><%= link_to "Personal Website", @candidate.portfolio_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.projects_link %>
            <li><%= link_to "Blog/PortFolio", @candidate.projects_link, target: "_blank" %></li>
          <% end %>
          <% if @candidate.linkedin_url %>
            <li><%= link_to "Linkedin", "http://linkedin.com/in/" + @candidate.linkedin_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.twitter_url %>
            <li><%= link_to "Twitter", "http://twitter.com/" + @candidate.twitter_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.github_url %>
            <li><%= link_to "Github", "http://github.com/" + @candidate.github_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.facebook_url %>
            <li><%= link_to "Facebook", "http://facebook.com/" + @candidate.facebook_url, target: "_blank"  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
  </div>
  
  <div class='medium-9 small-12 columns edit-works'>

    <div class='edit-form'>
        <h2 class='text-center'>Update Your Account</h2><br>
         <%#= render 'form' %>
         <%= form_for(@candidate) do |f| %>
          <%= render "shared/errors", object: @candidate %>

        <div class="form-group">
          <%= f.text_field :name, size: 50, autofocus: true, placeholder: "Your Full Name" %>
        </div>

        <div class="form-group">
            <%= f.text_field :username, size: 50,
                      placeholder: "Username Alphanumeric characters only!" %>
        </div>

        <div class="row">
          <div class='medium-8 small-6 columns'>
            <%= f.email_field :email, size: 50, placeholder: "Email Address" %>
          </div>
          <div class='medium-3 small-4 columns'>
            <%= f.select :email_status, Candidate::PROFILE_STATUS, prompt: "Email Status", class: "form-control" %>
          </div>
          <div class='medium-1 small-2 columns'>
            <span data-tooltip aria-haspopup="true" class="has-tip" title="Select for email status either to be displayed Public or Private (Hide from public)"><i class='fa fa-info'></i></span>
          </div>
        </div>

       <div class="form-group">
          <%= f.password_field :password, size: 50, placeholder: "Password 8 or more characters" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password_confirmation, size: 50, placeholder: "Confirm Password" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Account", class: "success hollow button" %>
        </div>
      <% end %>

    </div>
  </div>
</div>
  

app/views/candidates/index.html.erb
<div class='row'><br>

  <% if @candidates.any? %>
    <%# @candidates.in_groups_of(3) do |group| %>
      <div class='row candidate-home'>
        <% @candidates.each do |candidate| %>
          <% if candidate %>
            <div class='large-4 medium-6 small-12 columns'>
              <% if candidate.profile_status == "PUBLIC" %>
                <div class='row'>
                  <div class='medium-4 small-5 columns'>
                    <% if candidate.cand_image_url %>
                      <%= image_tag candidate.cand_image_url %>
                    <% else %>
                      <i class='fa fa-user fa-4x'></i>
                    <% end %>
                  </div>
                  <div class='medium-8 small-7 colums cand-content'>
                    <h4><%= link_to candidate.name, candidate %></h4>
                    <h5><%= candidate.email if candidate.email_status == "PUBLIC" %></h5>
                    <h5><%= candidate.city %></h5>
                    <h5><%= candidate.phone_number if candidate.phone_status == "PUBLIC" %></h5>
                  </div>
                </div><br>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <%# end %>
  <% end %>
</div>

app/views/candidates/new.html.erb
<div class='candidate-new'>
  <div class='row'>
    <br>
    <div class='medium-6 small-12 columns'>
      <h1>
        Register to connect with other applicants and browse thousands of jobs.
      </h1>
    </div>
    <div class='medium-6 small-12 columns'>
      <h2>Unlock Your Free Account</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div class='edit-candidates'>
  <div class='medium-3 columns hide-for-small-only'>
    <br><br>
    <div class='cand-profile-image'>
      <% if @candidate.cand_image_url %>
        <%= image_tag @candidate.cand_image_url %>
      <% else %>
        <%= profile_image_for@candidate %></p>
      <% end %>
    </div>
    <div><%= render 'contact_candidate' %></div>
    <%#= @candidate.image_url %>
    <%#= @candidate.headline %>
    <% if current_candidate?(@candidate) %>
      <div class='candidate-edit-nav'>
        <ul>
          <li>
            </i><% if  @candidate.resume_url %>
              <i class='fa fa-briefcase'></i>
              <%= link_to "Résumé", @candidate.resume_url, :target => "_blank" if @candidate.resume_url  %>
            <% else %>
              </i><%= link_to "Upload Résumé", profile_info_path+"#resume" if current_candidate?(@candidate)  %>
            <% end %>
          </li>
          <li><%= link_to "Update Profile", profile_info_path(current_candidate) if current_candidate %></li>
          <li><%= link_to "Settings", edit_candidate_path(current_candidate) if current_candidate %></li>
          <% if @candidate.portfolio_url %> 
            <li><%= link_to "Personal Website", @candidate.portfolio_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.projects_link %>
            <li><%= link_to "Blog/PortFolio", @candidate.projects_link, target: "_blank" %></li>
          <% end %>
          <% if @candidate.linkedin_url %>
            <li><%= link_to "Linkedin", "http://linkedin.com/in/" + @candidate.linkedin_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.twitter_url %>
            <li><%= link_to "Twitter", "http://twitter.com/" + @candidate.twitter_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.github_url %>
            <li><%= link_to "Github", "http://github.com/" + @candidate.github_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.facebook_url %>
            <li><%= link_to "Facebook", "http://facebook.com/" + @candidate.facebook_url, target: "_blank"  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
  </div>

   <div class='small-12 columns hide-for-medium-up'>
    <% if current_candidate?(@candidate) %>
      <div class='candidate-edit-nav-vertical'>
        <ul>
          <li>
            </i><% if  @candidate.resume_url %>
              <i class='fa fa-briefcase'></i>
              <%= link_to "Résumé", @candidate.resume_url, :target => "_blank" if @candidate.resume_url  %>
            <% else %>
              </i><%= link_to "Upload Résumé", profile_info_path+"#resume" if current_candidate?(@candidate)  %>
            <% end %>
          </li>
          <li><%= link_to "Update Profile", profile_info_path(current_candidate) if current_candidate %></li>
          <li><%= link_to "Settings", edit_candidate_path(current_candidate) if current_candidate %></li>
          <% if @candidate.portfolio_url %> 
            <li><%= link_to "Personal Website", @candidate.portfolio_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.projects_link %>
            <li><%= link_to "Blog/PortFolio", @candidate.projects_link, target: "_blank" %></li>
          <% end %>
          <% if @candidate.linkedin_url %>
            <li><%= link_to "Linkedin", "http://linkedin.com/in/" + @candidate.linkedin_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.twitter_url %>
            <li><%= link_to "Twitter", "http://twitter.com/" + @candidate.twitter_url, target: "_blank"  %></li>
          <% end %>
          <% if @candidate.github_url %>
            <li><%= link_to "Github", "http://github.com/" + @candidate.github_url, target: "_blank" %></li>
          <% end %>
          <% if @candidate.facebook_url %>
            <li><%= link_to "Facebook", "http://facebook.com/" + @candidate.facebook_url, target: "_blank"  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
  </div>
  
  <div class='medium-9 small-12 columns show-content'>
    <div class='row'>
      <div class='medium-8 small-12 columns'>
        <h2><%= @candidate.name %></h2>
        <% if @candidate.email_status == "PUBLIC" %>
          <h4><%= @candidate.email %></h4>
        <% end %>

        <% if @candidate.facebook_url? || @candidate.twitter_url? || @candidate.github_url? || @candidate.linkedin_url? || @candidate.dribbble_url?%>
      
          <div class='company-social-candidate'>
            <div class='social-link facebook'>
              <%= link_to "", "https://www.facebook.com/#{@candidate.facebook_url}", :target => "_blank", class: "fa fa-facebook fa-2x" if @candidate.facebook_url? %>
            </div>
            <div class='social-link linkedin'>
              <%= link_to "", "https://www.linkedin.com/in/#{@candidate.linkedin_url}", :target => "_blank", class: "fa fa-linkedin fa-2x" if @candidate.linkedin_url? %>
            </div>
            <div class='social-link twitter'>
              <%= link_to "", "https://www.twitter.com/{@candidate.twitter_url}", :target => "_blank", class: "fa fa-twitter fa-2x" if @candidate.twitter_url? %>
            </div>
            <div class='social-link dribbble'>
              <%= link_to "", "https://www.dribbble.com/#{@candidate.dribbble_url}", :target => "_blank", class: "fa fa-dribbble fa-2x" if @candidate.dribbble_url? %>
            </div>
            <div class='social-link github'>
              <%= link_to "", "https://www.github.com/#{@candidate.github_url}", :target => "_blank", class: "fa fa-github-alt fa-2x" if @candidate.github_url? %>
            </div>
          </div>
        <% end %>
        <% if @candidate.city %>
          <h4>Based in <%= @candidate.city %></h4>
        <% end %>

        <% if @works.any? %> 
        <hr>
          <h1>Work Experience</h1> 
          <% @works.each do |w| %>
            <div class='row cand-works-exp'>
              <div class='small-12 columns'>
                <h4><i class=" fa fa-briefcase " ></i><%= w.company %></h4>
              </div>
              <!-- <div class='row'> -->
                <div class='medium-9 small-8 columns'>
                  <%= w.position %>
                </div>
                <%if current_candidate?(@candidate) %>
                  <div class='medium-3 small-4 columns'>
                    <%= link_to "Edit", edit_candidate_work_path(@candidate, w) %> 
                    <%= link_to 'Delete', candidate_work_path(@candidate, w), method: :delete, data: {confirm: "Are You Sure?"} %>
                  </div>
                <% end %>
              <!-- </div> -->
              <div class='small-12 columns'>
                <%= w.start_month %> <%= w.start_year %> — 
                <% if w.status == "CURRENT" %> 
                  <%= "present" %>
                <% else %>
                  <%= w.end_month %> <%= w.end_year %>
                <% end %>
              </div>
              
              <div class='medium-12 small-12 columns'>
                <%= w.description %>
              </div>
            </div>
          <% end %>
        <% end %>   
        
        <% if @educations.any? %>  
          <hr>
          <h1>Education</h1>
          <% @educations.each do |e| %>
            <div class='row'>
              <div class='medium-9 small-8 columns'>
                <h5><%= e.school %></h5>
              </div>
              <div class='medium-3 small-4 columns'>
                <%if current_candidate?(@candidate) %>
                  <%= link_to "Edit", edit_candidate_education_path(@candidate, e) %> 
                  <%= link_to 'Delete', candidate_education_path(@candidate, e), method: :delete, data: {confirm: "Are You Sure?"} %>
                <% end %>
              </div>
              <div class='medium-9 small-8 columns'>
                <h5><%= e.degree %></h5>
              </div>
              <div class='medium-3 small-4 columns'>
                <h5><%= e.year %> 
              </div>
            </div><br>  
          <% end %>
        <% end %>
      </div>
      <div class='medium-4 small-12 columns candidate-aside'>
        <% if @followed_companies.any? %>
          <div class='show-aside candidate-followed'>
            <h2>Followed Companies</h2>
            
            <div class='row'>
              <% @followed_companies.each do |company| %>
                <div class='large-3 medium-6 small-3 columns'>
                  <%= link_to(image_tag(company.logo_url), company) %>
                  <%# if company.logo_url %>
                    <%#= link_to company.name, company 
                     
                  <%# end %>
                </div>
              <% end %>
            </div>
            
          </div>
        <% end %>
        
        <% if @jobs %>
          <div class='show-aside'>
            <h2>Latest Jobs</h2>
            <% @jobs.limit(5).each do |job| %>
              <div id='candidate-all-job'>
                <h3><%= link_to job.title, job %></h3>
                <span><%= job.company_name %></span><br>
                <span><%= job.city if job.city %>, &nbsp; <%= job.state if job.state %> &nbsp; <%= job.zip_code if job.zip_code  %></span>
              </div> 
            <% end %> 
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
</div>